---
title: "Hawkin API Import"
output: html_document
---

```{r setup, include=FALSE}
library(hawkinR)
library(dplyr)
library(writexl)
library(cmstatr)
```

```{r}
api_url <- "https://cloud.hawkindynamics.com/api"

refreshToken <- "YCOShw.nZAnDlsYMlw8eW16Nr82DkwlKe66g"

get_access(refreshToken, region = "Americas")
```


```{r}
# types of tests 
testIds <- get_testTypes()
testIds

# only keep tests starting from june 3rd, 2024 
fromDate <- as.numeric(as.POSIXct("2024-06-03", tz = "UTC"))
# only keep CMJ tests 
testId <- "7nNduHeM5zETPjHxvm7s" 

# create df with tests 
cmj_tests <- get_tests(typeId = testId, from = fromDate)
# head(cmj_tests)
# summary(cmj_tests)
unique(cmj_tests$testType_name) 

cmj_tests <- cmj_tests %>%
  filter(testType_name %in% c("Countermovement Jump", "Countermovement Jump-CMJ")) # %>% 
  #select(-athlete_c_mfsh_xql_ex_qvagn_q_zn1jcfsvloo2)

#cmj_tests <- na.omit(cmj_tests)

# summary(cmj_tests) 
# 6453 CMJ tests since June 3rd
```


```{r}
# using numeric columns only 
data_numeric <- dplyr::select_if(cmj_tests, is.numeric)

data_numeric <- data_numeric %>% 
  select(-timestamp, -last_test_time, -last_sync_time)


# Taking out these 2 rows gives us 3840 more jumps of data 
data_numeric <- data_numeric %>% 
  select(-time_to_stabilization_ms, -l_r_landing_impulse_index_percent)


# summary(data_numeric)

data_numeric <- na.omit(data_numeric)

# summary(data_numeric)

nrow(data_numeric)

data_numeric <- data_numeric %>%
  mutate(across(everything(), as.double))

data_numeric <- data_numeric %>%
  mutate(left_force_at_peak_propulsive_force_n = as.double(left_force_at_peak_propulsive_force_n)) %>%
  mutate(right_force_at_peak_braking_force_n = as.double(right_force_at_peak_braking_force_n)) %>%
  mutate(force_at_min_displacement_n = as.double(force_at_min_displacement_n)) %>%
  mutate(peak_landing_force_n = as.double(peak_landing_force_n)) %>%
  mutate(peak_braking_force_n = as.double(peak_braking_force_n)) %>%
  mutate(right_force_at_peak_propulsive_force_n = as.double(right_force_at_peak_propulsive_force_n)) %>%
  mutate(right_force_at_peak_landing_force_n = as.double(right_force_at_peak_landing_force_n))%>%
  mutate(peak_propulsive_force_n = as.double(peak_propulsive_force_n)) %>%
  mutate(left_force_at_peak_landing_force_n = as.double(left_force_at_peak_landing_force_n)) %>%
  mutate(left_force_at_peak_braking_force_n = as.double(left_force_at_peak_braking_force_n))


```
### 2708 tests with non NA values in "time_to_stabilization_ms" and "l_r_landing_impulse_index_percent"  

### Without them, we have 6548 tests of data 


```{r}
# summary(data_numeric)

# function to calculate coefficient of variation (sd / mean)
calc_cv <- function(x) {
  if (mean(x, na.rm = TRUE) != 0) {
    return(sd(x, na.rm = TRUE) / mean(x, na.rm = TRUE))
  } else {
    return(NA)
  }
}

# df of what we want 
results <- data.frame(
  Metric = colnames(data_numeric),
  "Correlation to Jump Height" = sapply(data_numeric, function(x) cor(x, data_numeric$jump_height_m, use = "complete.obs")),
  "Coefficient of Variance" = sapply(data_numeric, calc_cv)
)

# export to excel file 
# writexl::write_xlsx(results, "JumpHeight.xlsx")
```

```{r}
# keep columns we are looking at  
compare_to_rfd <- data_numeric %>% 
  select("braking_rfd_n_s", "peak_braking_force_n", "time_to_takeoff_s", "braking_net_impulse_n_s", 
         "peak_braking_velocity_m_s", "peak_braking_power_w", "m_rsi")


# summary(compare_to_rfd)

# df of what we want 
results1 <- data.frame(
  Metric = colnames(compare_to_rfd),
  "Correlation to RFD" = sapply(compare_to_rfd, function(x) cor(x, compare_to_rfd$braking_rfd_n_s, use = "complete.obs")),
  "Coefficient of Variance" = sapply(compare_to_rfd, calc_cv)
)

# export to excel 
# writexl::write_xlsx(results1, "BreakingRFD.xlsx")
```

we are looking for a metric with: low coefficient of variance, high correlation, in eccentric category - something that will work better than rfd 

